server:
  port: 9090

spring:
  application:
    name: basic
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/subscription?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    initialization-mode: always
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 10
#  rabbitmq:
#    host: localhost
#    virtualHost: tmn-th-alpha
#    port: 15672
#    password: guest
#    username: guest
#    exchange: numbers
#    queue: numbers
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        id:
#          new_generator_mappings: false

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      username: guest
      password: guest
      exchange: emails
      queue: emails

subscription-service:
  api-key-header: "x-api-key"
  api-key-value: "cb4532fc26b9421d88c5a079288bf51e"
  correlation-id-key: "X-Correlation-ID"
  role: "ROLE_SERVICE"
