server:
  port: 9090

spring:
  application:
    name: basic
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3307/subscription?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:subscription_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    initialization-mode: always
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 10
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        id:
#          new_generator_mappings: false

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      username: guest
      password: guest
      exchange: emails
      queue: emails

subscription-service:
  api-key-header: "x-api-key"
  api-key-value: "cb4532fc26b9421d88c5a079288bf51e"
  correlation-id-key: "X-Correlation-ID"
  role: "ROLE_SERVICE"
